from .IDetectionNetworkController import IDetectionNetworkController, BBox
from .YoloDetectionNetworkController import YoloDetectionNetworkController
from .YoloDetectionNetworkControllerM import YoloDetectionNetworkControllerM