# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(432, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.testImageButton = QtWidgets.QPushButton(self.groupBox_2)
        self.testImageButton.setObjectName("testImageButton")
        self.gridLayout_3.addWidget(self.testImageButton, 3, 0, 1, 1)
        self.ImageLabel = QtWidgets.QLabel(self.groupBox_2)
        self.ImageLabel.setMinimumSize(QtCore.QSize(96, 96))
        self.ImageLabel.setText("")
        self.ImageLabel.setObjectName("ImageLabel")
        self.gridLayout_3.addWidget(self.ImageLabel, 1, 1, 1, 1)
        self.loadImageButton = QtWidgets.QPushButton(self.groupBox_2)
        self.loadImageButton.setObjectName("loadImageButton")
        self.gridLayout_3.addWidget(self.loadImageButton, 1, 0, 1, 1)
        self.ImageDetectedClassLabel = QtWidgets.QLabel(self.groupBox_2)
        self.ImageDetectedClassLabel.setText("")
        self.ImageDetectedClassLabel.setObjectName("ImageDetectedClassLabel")
        self.gridLayout_3.addWidget(self.ImageDetectedClassLabel, 3, 1, 1, 1)
        self.modelsComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.modelsComboBox.setObjectName("modelsComboBox")
        self.gridLayout_3.addWidget(self.modelsComboBox, 0, 1, 1, 1)
        self.loadModelButton = QtWidgets.QPushButton(self.groupBox_2)
        self.loadModelButton.setObjectName("loadModelButton")
        self.gridLayout_3.addWidget(self.loadModelButton, 0, 0, 1, 1)
        self.ImageClassLabel = QtWidgets.QLabel(self.groupBox_2)
        self.ImageClassLabel.setText("")
        self.ImageClassLabel.setObjectName("ImageClassLabel")
        self.gridLayout_3.addWidget(self.ImageClassLabel, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.trainModelButton = QtWidgets.QPushButton(self.groupBox)
        self.trainModelButton.setObjectName("trainModelButton")
        self.gridLayout_2.addWidget(self.trainModelButton, 6, 0, 1, 3)
        self.AugRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.AugRadioButton.setObjectName("AugRadioButton")
        self.gridLayout_2.addWidget(self.AugRadioButton, 5, 2, 1, 1)
        self.learningAlgComboBox = QtWidgets.QComboBox(self.groupBox)
        self.learningAlgComboBox.setObjectName("learningAlgComboBox")
        self.gridLayout_2.addWidget(self.learningAlgComboBox, 1, 2, 1, 1)
        self.LearningRateSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.LearningRateSpinBox.setDecimals(5)
        self.LearningRateSpinBox.setSingleStep(5e-05)
        self.LearningRateSpinBox.setProperty("value", 1e-05)
        self.LearningRateSpinBox.setObjectName("LearningRateSpinBox")
        self.gridLayout_2.addWidget(self.LearningRateSpinBox, 2, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.BatchSizeSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.BatchSizeSpinBox.setMaximum(500)
        self.BatchSizeSpinBox.setSingleStep(50)
        self.BatchSizeSpinBox.setProperty("value", 100)
        self.BatchSizeSpinBox.setObjectName("BatchSizeSpinBox")
        self.gridLayout_2.addWidget(self.BatchSizeSpinBox, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.epochsSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.epochsSpinBox.setMinimum(5)
        self.epochsSpinBox.setMaximum(150)
        self.epochsSpinBox.setObjectName("epochsSpinBox")
        self.gridLayout_2.addWidget(self.epochsSpinBox, 4, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 432, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Распознавание летательной техники"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Использование модели"))
        self.testImageButton.setText(_translate("MainWindow", "Определить класс самолета"))
        self.loadImageButton.setText(_translate("MainWindow", "Загрузить изображение"))
        self.loadModelButton.setText(_translate("MainWindow", "Загрузить модель"))
        self.groupBox.setTitle(_translate("MainWindow", "Обучение модели"))
        self.trainModelButton.setText(_translate("MainWindow", "Обучить модель"))
        self.AugRadioButton.setText(_translate("MainWindow", "Аугментация"))
        self.label_2.setText(_translate("MainWindow", "Алгоритм обучения:"))
        self.label_4.setText(_translate("MainWindow", "Размер батча:"))
        self.label.setText(_translate("MainWindow", "Название модели:"))
        self.label_3.setText(_translate("MainWindow", "Скорость обучения:"))
        self.label_5.setText(_translate("MainWindow", "Максимально число эпох:"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
